### ISSUE TITLE
Submit ztreamy to PyPi

### ISSUE THREAD

**Issue by jvrplmlmn** [jfisteus/ztreamy#15]
Uploading it to PyPi will make it easier to distribute the project, which could bring more exposure.

Also, if in near future we extract the examples to a different repo, we can always leverage ztreamy as a requirement, making the dependencies of the core project smaller.

**Comment by jvrplmlmn** [comment]
Almost all the effort is already done, we have a `setup.py` file and the project has tags for the versions.

I need to look further into some extra settings for `setup.py`, I don't know if the `COPYING.TXT` license file that we have could be linked, or we would need to rename it to `LICENSE`.

If additional changes are needed, I'd open a PR.

Related info:

http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by jvrplmlmn** [comment]
`MANIFEST.in`:

https://docs.python.org/2/distutils/sourcedist.html
https://www.digitalocean.com/community/tutorials/how-to-package-and-distribute-python-applications

**Comment by jvrplmlmn** [comment]
There was a typo in the title of this issue, don't mix PyPy with PyPi!

**Comment by jvrplmlmn** [comment]
I did a small test, using PyPi test. The needed steps are:

1) Register in PyPi Test:

https://testpypi.python.org/pypi?%3Aaction=register_form

The confirmation mail takes 3-5 minutes, in the meantime, you could jump to step 2.

2) Create a `~/.pypirc` file, in this case you can omit the pypi section.

```
[distutils]
index-servers=
    pypi
    pypitest

[pypi]
repository = https://pypi.python.org/pypi
username = <username>
password = <password>

[pypitest]
repository = https://testpypi.python.org/pypi
username = <username>
password = <password>
```

3) Inside the repo directory, run to register the project:

    python setup.py register -r pypitest

4) To upload the project to TestPypi, run:

    python setup.py sdist upload -r pypitest

----

After uploading it to test PyPi, I tested the installation:

```
➜  ztreamy-test  virtualenv venv
New python executable in venv/bin/python
Installing setuptools, pip...done.
➜  ztreamy-test  . venv/bin/activate                                                   
(venv)➜  ztreamy-test  pip freeze
argparse==1.2.1
wsgiref==0.1.2
(venv)➜  ztreamy-test  echo "import ztreamy" > test.py
(venv)➜  ztreamy-test  python test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import ztreamy
ImportError: No module named ztreamy
(venv)➜  ztreamy-test  

(venv)➜  ztreamy-test  pip install --extra-index-url https://testpypi.python.org/pypi ztreamy
Downloading/unpacking ztreamy

(...)
Successfully installed ztreamy tornado rdflib rdfextras rdflib-jsonld tweepy pycurl pyparsing httplib2 simplejson certifi backports.ssl-match-hostname isodate SPARQLWrapper html5lib six
Cleaning up...
(venv)➜  ztreamy-test  

(venv)➜  ztreamy-test  python test.py                                                        
(venv)➜  ztreamy-test  

```

It works!

**Comment by jvrplmlmn** [comment]
We're missing some metadata in the `setup.py` file. I've opened #20 to take care of the `license` field.

**Comment by jfisteus** [comment]
Thanks. I'll do the upload as soon as I can.

**Comment by jfisteus** [comment]
The package is now installable from PyPI as ztreamy 0.3.1. I need now to update installation instructions and announce the release in the website.

https://pypi.python.org/pypi/ztreamy/

**Comment by jvrplmlmn** [comment]
Fantastic news! :+1:

**Comment by jfisteus** [comment]
I've updated the documentation and the website. See commits b322b76ed2334756a37456116ab6e823a76bd132 and 7faf59da653723db7d5b57a2bc423b7578273b19.
